INSERT INTO users (name, age) VALUES ("Brandon", 26);
INSERT INTO users (name, age) VALUES ("Desiree", 24);
INSERT INTO users (name, age) VALUES ("Norma", 52);
INSERT INTO users (name, age) VALUES ("Terri", 57);
INSERT INTO users (name, age) VALUES ("Emmanuel", 22);
INSERT INTO users (name, age) VALUES ("Damien", 21);
INSERT INTO users (name, age) VALUES ("Orlando", 60);
INSERT INTO users (name, age) VALUES ("Dave", 78);
INSERT INTO users (name, age) VALUES ("Kevin", 61);
INSERT INTO users (name, age) VALUES ("Wayne", 50);
INSERT INTO users (name, age) VALUES ("John", 26);
INSERT INTO users (name, age) VALUES ("Justin", 26);
INSERT INTO users (name, age) VALUES ("Tara", 36);
INSERT INTO users (name, age) VALUES ("Josephine", 53);
INSERT INTO users (name, age) VALUES ("Tiffany", 46);
INSERT INTO users (name, age) VALUES ("Dee", 38);
INSERT INTO users (name, age) VALUES ("Shannon", 37);
INSERT INTO users (name, age) VALUES ("Scott", 59);
INSERT INTO users (name, age) VALUES ("Brandon", 37);
INSERT INTO users (name, age) VALUES ("Alec", 25);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("I", "Medical", 50000, "January", "Febuary");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Do", "Research", 50000, "Febuary", "March");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Not", "Educational", 50000, "March", "April");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Want", "Medical", 50000, "April", "May");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("To", "Medical", 50000, "May", "June");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Name", "Reaserch", 50000, "June", "July");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("All", "Educational", 50000, "July", "August");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Of", "Educational", 50000, "August", "September");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("These", "Political", 50000, "September", "October");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Saint Judes", "Medical", 50000, "November", "December");

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5090, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (52300, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 11, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 10, 2);
